export const ALL_COUNTRY_CODES = [
  { country: 'AF', code: '+93', label: 'Afghanistan (+93)' },
  { country: 'AL', code: '+355', label: 'Albania (+355)' },
  { country: 'DZ', code: '+213', label: 'Algeria (+213)' },
  { country: 'AS', code: '+1684', label: 'American Samoa (+1684)' },
  { country: 'AD', code: '+376', label: 'Andorra (+376)' },
  { country: 'AO', code: '+244', label: 'Angola (+244)' },
  { country: 'AI', code: '+1264', label: 'Anguilla (+1264)' },
  { country: 'AQ', code: '+672', label: 'Antarctica (+672)' },
  { country: 'AG', code: '+1268', label: 'Antigua and Barbuda (+1268)' },
  { country: 'AR', code: '+54', label: 'Argentina (+54)' },
  { country: 'AM', code: '+374', label: 'Armenia (+374)' },
  { country: 'AW', code: '+297', label: 'Aruba (+297)' },
  { country: 'AU', code: '+61', label: 'Australia (+61)' },
  { country: 'AT', code: '+43', label: 'Austria (+43)' },
  { country: 'AZ', code: '+994', label: 'Azerbaijan (+994)' },
  { country: 'BS', code: '+1242', label: 'Bahamas (+1242)' },
  { country: 'BH', code: '+973', label: 'Bahrain (+973)' },
  { country: 'BD', code: '+880', label: 'Bangladesh (+880)' },
  { country: 'BB', code: '+1246', label: 'Barbados (+1246)' },
  { country: 'BY', code: '+375', label: 'Belarus (+375)' },
  { country: 'BE', code: '+32', label: 'Belgium (+32)' },
  { country: 'BZ', code: '+501', label: 'Belize (+501)' },
  { country: 'BJ', code: '+229', label: 'Benin (+229)' },
  { country: 'BM', code: '+1441', label: 'Bermuda (+1441)' },
  { country: 'BT', code: '+975', label: 'Bhutan (+975)' },
  { country: 'BO', code: '+591', label: 'Bolivia (+591)' },
  { country: 'BA', code: '+387', label: 'Bosnia and Herzegovina (+387)' },
  { country: 'BW', code: '+267', label: 'Botswana (+267)' },
  { country: 'BR', code: '+55', label: 'Brazil (+55)' },
  { country: 'IO', code: '+246', label: 'British Indian Ocean Territory (+246)' },
  { country: 'VG', code: '+1284', label: 'British Virgin Islands (+1284)' },
  { country: 'BN', code: '+673', label: 'Brunei (+673)' },
  { country: 'BG', code: '+359', label: 'Bulgaria (+359)' },
  { country: 'BF', code: '+226', label: 'Burkina Faso (+226)' },
  { country: 'BI', code: '+257', label: 'Burundi (+257)' },
  { country: 'KH', code: '+855', label: 'Cambodia (+855)' },
  { country: 'CM', code: '+237', label: 'Cameroon (+237)' },
  { country: 'CA', code: '+1', label: 'Canada (+1)' },
  { country: 'CV', code: '+238', label: 'Cape Verde (+238)' },
  { country: 'KY', code: '+1345', label: 'Cayman Islands (+1345)' },
  { country: 'CF', code: '+236', label: 'Central African Republic (+236)' },
  { country: 'TD', code: '+235', label: 'Chad (+235)' },
  { country: 'CL', code: '+56', label: 'Chile (+56)' },
  { country: 'CN', code: '+86', label: 'China (+86)' },
  { country: 'CX', code: '+61', label: 'Christmas Island (+61)' },
  { country: 'CC', code: '+61', label: 'Cocos Islands (+61)' },
  { country: 'CO', code: '+57', label: 'Colombia (+57)' },
  { country: 'KM', code: '+269', label: 'Comoros (+269)' },
  { country: 'CK', code: '+682', label: 'Cook Islands (+682)' },
  { country: 'CR', code: '+506', label: 'Costa Rica (+506)' },
  { country: 'HR', code: '+385', label: 'Croatia (+385)' },
  { country: 'CU', code: '+53', label: 'Cuba (+53)' },
  { country: 'CW', code: '+599', label: 'Curacao (+599)' },
  { country: 'CY', code: '+357', label: 'Cyprus (+357)' },
  { country: 'CZ', code: '+420', label: 'Czech Republic (+420)' },
  { country: 'CD', code: '+243', label: 'Democratic Republic of the Congo (+243)' },
  { country: 'DK', code: '+45', label: 'Denmark (+45)' },
  { country: 'DJ', code: '+253', label: 'Djibouti (+253)' },
  { country: 'DM', code: '+1767', label: 'Dominica (+1767)' },
  { country: 'DO', code: '+1809', label: 'Dominican Republic (+1809)' },
  { country: 'TL', code: '+670', label: 'East Timor (+670)' },
  { country: 'EC', code: '+593', label: 'Ecuador (+593)' },
  { country: 'EG', code: '+20', label: 'Egypt (+20)' },
  { country: 'SV', code: '+503', label: 'El Salvador (+503)' },
  { country: 'GQ', code: '+240', label: 'Equatorial Guinea (+240)' },
  { country: 'ER', code: '+291', label: 'Eritrea (+291)' },
  { country: 'EE', code: '+372', label: 'Estonia (+372)' },
  { country: 'ET', code: '+251', label: 'Ethiopia (+251)' },
  { country: 'FK', code: '+500', label: 'Falkland Islands (+500)' },
  { country: 'FO', code: '+298', label: 'Faroe Islands (+298)' },
  { country: 'FJ', code: '+679', label: 'Fiji (+679)' },
  { country: 'FI', code: '+358', label: 'Finland (+358)' },
  { country: 'FR', code: '+33', label: 'France (+33)' },
  { country: 'PF', code: '+689', label: 'French Polynesia (+689)' },
  { country: 'GA', code: '+241', label: 'Gabon (+241)' },
  { country: 'GM', code: '+220', label: 'Gambia (+220)' },
  { country: 'GE', code: '+995', label: 'Georgia (+995)' },
  { country: 'DE', code: '+49', label: 'Germany (+49)' },
  { country: 'GH', code: '+233', label: 'Ghana (+233)' },
  { country: 'GI', code: '+350', label: 'Gibraltar (+350)' },
  { country: 'GR', code: '+30', label: 'Greece (+30)' },
  { country: 'GL', code: '+299', label: 'Greenland (+299)' },
  { country: 'GD', code: '+1473', label: 'Grenada (+1473)' },
  { country: 'GU', code: '+1671', label: 'Guam (+1671)' },
  { country: 'GT', code: '+502', label: 'Guatemala (+502)' },
  { country: 'GG', code: '+44', label: 'Guernsey (+44)' },
  { country: 'GN', code: '+224', label: 'Guinea (+224)' },
  { country: 'GW', code: '+245', label: 'Guinea-Bissau (+245)' },
  { country: 'GY', code: '+592', label: 'Guyana (+592)' },
  { country: 'HT', code: '+509', label: 'Haiti (+509)' },
  { country: 'HN', code: '+504', label: 'Honduras (+504)' },
  { country: 'HK', code: '+852', label: 'Hong Kong (+852)' },
  { country: 'HU', code: '+36', label: 'Hungary (+36)' },
  { country: 'IS', code: '+354', label: 'Iceland (+354)' },
  { country: 'IN', code: '+91', label: 'India (+91)' },
  { country: 'ID', code: '+62', label: 'Indonesia (+62)' },
  { country: 'IR', code: '+98', label: 'Iran (+98)' },
  { country: 'IQ', code: '+964', label: 'Iraq (+964)' },
  { country: 'IE', code: '+353', label: 'Ireland (+353)' },
  { country: 'IM', code: '+44', label: 'Isle of Man (+44)' },
  { country: 'IL', code: '+972', label: 'Israel (+972)' },
  { country: 'IT', code: '+39', label: 'Italy (+39)' },
  { country: 'CI', code: '+225', label: 'Ivory Coast (+225)' },
  { country: 'JM', code: '+1876', label: 'Jamaica (+1876)' },
  { country: 'JP', code: '+81', label: 'Japan (+81)' },
  { country: 'JE', code: '+44', label: 'Jersey (+44)' },
  { country: 'JO', code: '+962', label: 'Jordan (+962)' },
  { country: 'KZ', code: '+7', label: 'Kazakhstan (+7)' },
  { country: 'KE', code: '+254', label: 'Kenya (+254)' },
  { country: 'KI', code: '+686', label: 'Kiribati (+686)' },
  { country: 'XK', code: '+383', label: 'Kosovo (+383)' },
  { country: 'KW', code: '+965', label: 'Kuwait (+965)' },
  { country: 'KG', code: '+996', label: 'Kyrgyzstan (+996)' },
  { country: 'LA', code: '+856', label: 'Laos (+856)' },
  { country: 'LV', code: '+371', label: 'Latvia (+371)' },
  { country: 'LB', code: '+961', label: 'Lebanon (+961)' },
  { country: 'LS', code: '+266', label: 'Lesotho (+266)' },
  { country: 'LR', code: '+231', label: 'Liberia (+231)' },
  { country: 'LY', code: '+218', label: 'Libya (+218)' },
  { country: 'LI', code: '+423', label: 'Liechtenstein (+423)' },
  { country: 'LT', code: '+370', label: 'Lithuania (+370)' },
  { country: 'LU', code: '+352', label: 'Luxembourg (+352)' },
  { country: 'MO', code: '+853', label: 'Macau (+853)' },
  { country: 'MK', code: '+389', label: 'Macedonia (+389)' },
  { country: 'MG', code: '+261', label: 'Madagascar (+261)' },
  { country: 'MW', code: '+265', label: 'Malawi (+265)' },
  { country: 'MY', code: '+60', label: 'Malaysia (+60)' },
  { country: 'MV', code: '+960', label: 'Maldives (+960)' },
  { country: 'ML', code: '+223', label: 'Mali (+223)' },
  { country: 'MT', code: '+356', label: 'Malta (+356)' },
  { country: 'MH', code: '+692', label: 'Marshall Islands (+692)' },
  { country: 'MR', code: '+222', label: 'Mauritania (+222)' },
  { country: 'MU', code: '+230', label: 'Mauritius (+230)' },
  { country: 'YT', code: '+262', label: 'Mayotte (+262)' },
  { country: 'MX', code: '+52', label: 'Mexico (+52)' },
  { country: 'FM', code: '+691', label: 'Micronesia (+691)' },
  { country: 'MD', code: '+373', label: 'Moldova (+373)' },
  { country: 'MC', code: '+377', label: 'Monaco (+377)' },
  { country: 'MN', code: '+976', label: 'Mongolia (+976)' },
  { country: 'ME', code: '+382', label: 'Montenegro (+382)' },
  { country: 'MS', code: '+1664', label: 'Montserrat (+1664)' },
  { country: 'MA', code: '+212', label: 'Morocco (+212)' },
  { country: 'MZ', code: '+258', label: 'Mozambique (+258)' },
  { country: 'MM', code: '+95', label: 'Myanmar (+95)' },
  { country: 'NA', code: '+264', label: 'Namibia (+264)' },
  { country: 'NR', code: '+674', label: 'Nauru (+674)' },
  { country: 'NP', code: '+977', label: 'Nepal (+977)' },
  { country: 'NL', code: '+31', label: 'Netherlands (+31)' },
  { country: 'AN', code: '+599', label: 'Netherlands Antilles (+599)' },
  { country: 'NC', code: '+687', label: 'New Caledonia (+687)' },
  { country: 'NZ', code: '+64', label: 'New Zealand (+64)' },
  { country: 'NI', code: '+505', label: 'Nicaragua (+505)' },
  { country: 'NE', code: '+227', label: 'Niger (+227)' },
  { country: 'NG', code: '+234', label: 'Nigeria (+234)' },
  { country: 'NU', code: '+683', label: 'Niue (+683)' },
  { country: 'KP', code: '+850', label: 'North Korea (+850)' },
  { country: 'MP', code: '+1670', label: 'Northern Mariana Islands (+1670)' },
  { country: 'NO', code: '+47', label: 'Norway (+47)' },
  { country: 'OM', code: '+968', label: 'Oman (+968)' },
  { country: 'PK', code: '+92', label: 'Pakistan (+92)' },
  { country: 'PW', code: '+680', label: 'Palau (+680)' },
  { country: 'PS', code: '+970', label: 'Palestine (+970)' },
  { country: 'PA', code: '+507', label: 'Panama (+507)' },
  { country: 'PG', code: '+675', label: 'Papua New Guinea (+675)' },
  { country: 'PY', code: '+595', label: 'Paraguay (+595)' },
  { country: 'PE', code: '+51', label: 'Peru (+51)' },
  { country: 'PH', code: '+63', label: 'Philippines (+63)' },
  { country: 'PN', code: '+870', label: 'Pitcairn (+870)' },
  { country: 'PL', code: '+48', label: 'Poland (+48)' },
  { country: 'PT', code: '+351', label: 'Portugal (+351)' },
  { country: 'PR', code: '+1', label: 'Puerto Rico (+1)' },
  { country: 'QA', code: '+974', label: 'Qatar (+974)' },
  { country: 'CG', code: '+242', label: 'Republic of the Congo (+242)' },
  { country: 'RE', code: '+262', label: 'Reunion (+262)' },
  { country: 'RO', code: '+40', label: 'Romania (+40)' },
  { country: 'RU', code: '+7', label: 'Russia (+7)' },
  { country: 'RW', code: '+250', label: 'Rwanda (+250)' },
  { country: 'BL', code: '+590', label: 'Saint Barthelemy (+590)' },
  { country: 'SH', code: '+290', label: 'Saint Helena (+290)' },
  { country: 'KN', code: '+1869', label: 'Saint Kitts and Nevis (+1869)' },
  { country: 'LC', code: '+1758', label: 'Saint Lucia (+1758)' },
  { country: 'MF', code: '+590', label: 'Saint Martin (+590)' },
  { country: 'PM', code: '+508', label: 'Saint Pierre and Miquelon (+508)' },
  { country: 'VC', code: '+1784', label: 'Saint Vincent and the Grenadines (+1784)' },
  { country: 'WS', code: '+685', label: 'Samoa (+685)' },
  { country: 'SM', code: '+378', label: 'San Marino (+378)' },
  { country: 'ST', code: '+239', label: 'Sao Tome and Principe (+239)' },
  { country: 'SA', code: '+966', label: 'Saudi Arabia (+966)' },
  { country: 'SN', code: '+221', label: 'Senegal (+221)' },
  { country: 'RS', code: '+381', label: 'Serbia (+381)' },
  { country: 'SC', code: '+248', label: 'Seychelles (+248)' },
  { country: 'SL', code: '+232', label: 'Sierra Leone (+232)' },
  { country: 'SG', code: '+65', label: 'Singapore (+65)' },
  { country: 'SX', code: '+1721', label: 'Sint Maarten (+1721)' },
  { country: 'SK', code: '+421', label: 'Slovakia (+421)' },
  { country: 'SI', code: '+386', label: 'Slovenia (+386)' },
  { country: 'SB', code: '+677', label: 'Solomon Islands (+677)' },
  { country: 'SO', code: '+252', label: 'Somalia (+252)' },
  { country: 'ZA', code: '+27', label: 'South Africa (+27)' },
  { country: 'KR', code: '+82', label: 'South Korea (+82)' },
  { country: 'SS', code: '+211', label: 'South Sudan (+211)' },
  { country: 'ES', code: '+34', label: 'Spain (+34)' },
  { country: 'LK', code: '+94', label: 'Sri Lanka (+94)' },
  { country: 'SD', code: '+249', label: 'Sudan (+249)' },
  { country: 'SR', code: '+597', label: 'Suriname (+597)' },
  { country: 'SJ', code: '+47', label: 'Svalbard and Jan Mayen (+47)' },
  { country: 'SZ', code: '+268', label: 'Swaziland (+268)' },
  { country: 'SE', code: '+46', label: 'Sweden (+46)' },
  { country: 'CH', code: '+41', label: 'Switzerland (+41)' },
  { country: 'SY', code: '+963', label: 'Syria (+963)' },
  { country: 'TW', code: '+886', label: 'Taiwan (+886)' },
  { country: 'TJ', code: '+992', label: 'Tajikistan (+992)' },
  { country: 'TZ', code: '+255', label: 'Tanzania (+255)' },
  { country: 'TH', code: '+66', label: 'Thailand (+66)' },
  { country: 'TG', code: '+228', label: 'Togo (+228)' },
  { country: 'TK', code: '+690', label: 'Tokelau (+690)' },
  { country: 'TO', code: '+676', label: 'Tonga (+676)' },
  { country: 'TT', code: '+1868', label: 'Trinidad and Tobago (+1868)' },
  { country: 'TN', code: '+216', label: 'Tunisia (+216)' },
  { country: 'TR', code: '+90', label: 'Turkey (+90)' },
  { country: 'TM', code: '+993', label: 'Turkmenistan (+993)' },
  { country: 'TC', code: '+1649', label: 'Turks and Caicos Islands (+1649)' },
  { country: 'TV', code: '+688', label: 'Tuvalu (+688)' },
  { country: 'VI', code: '+1340', label: 'U.S. Virgin Islands (+1340)' },
  { country: 'UG', code: '+256', label: 'Uganda (+256)' },
  { country: 'UA', code: '+380', label: 'Ukraine (+380)' },
  { country: 'AE', code: '+971', label: 'United Arab Emirates (+971)' },
  { country: 'UK', code: '+44', label: 'United Kingdom (+44)' },
  { country: 'US', code: '+1', label: 'United States (+1)' },
  { country: 'UY', code: '+598', label: 'Uruguay (+598)' },
  { country: 'UZ', code: '+998', label: 'Uzbekistan (+998)' },
  { country: 'VU', code: '+678', label: 'Vanuatu (+678)' },
  { country: 'VA', code: '+379', label: 'Vatican (+379)' },
  { country: 'VE', code: '+58', label: 'Venezuela (+58)' },
  { country: 'VN', code: '+84', label: 'Vietnam (+84)' },
  { country: 'WF', code: '+681', label: 'Wallis and Futuna (+681)' },
  { country: 'EH', code: '+212', label: 'Western Sahara (+212)' },
  { country: 'YE', code: '+967', label: 'Yemen (+967)' },
  { country: 'ZM', code: '+260', label: 'Zambia (+260)' },
  { country: 'ZW', code: '+263', label: 'Zimbabwe (+263)' }
];
